[server]
; IP untuk listen (0.0.0.0 = semua interface)
host = 0.0.0.0
; Port TCP untuk server
port = 9999
; Otomatis tambah Windows Firewall rule (true/false)
; Membutuhkan Run as Administrator
auto_firewall = true

[session]
; Default durasi sesi dalam menit
default_duration = 60
